package com.matrimony.model.enums;

public enum FoodPreference {
	ARABIC, BENGALI, CHINESE, CONTINENTAL, FAST_FOOD, GUJARATI, ITALIAN, KONKAN, MEXICAN, MOGHLAI, PUNJABI, RAJASTHANI,
	SOUTH_INDIAN, SPANISH, SUSHI
}
