package com.matrimony.model.enums;

public enum Hobby {
	ART_HANDICRAFT, COOKING, DANCING, GARDENING, NATURE, PAINTING, PETS, PHOTOGRAPHY, PLAYING_MUSICAL_INSTRUMENTS,
	PUZZLES, INTERNET_SURFING, LISTENING_TO_MUSIC, MOVIES, TRAVELLING
}
